name: marcket_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Necesario para que main.dart no de errores
  flutter_localizations:
    sdk: flutter

  # --- Utilidades Base ---
  # CAMBIO AQUÍ: Actualizado a 0.20.2 por requisito de Flutter
  intl: ^0.20.2
  collection: ^1.18.0
  path_provider: ^2.1.2
  url_launcher: ^6.3.0
  permission_handler: ^11.3.0

  # --- Firebase (Serie estable) ---
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_database: ^11.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0
  
  # --- Autenticación Social ---
  # Mantenemos 6.2.1 para que tu código actual funcione
  google_sign_in: ^6.2.1

  # --- UI & Animaciones ---
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^5.0.0

  # --- Archivos e Imágenes ---
  image_picker: ^1.1.2
  file_picker: ^8.0.0  
  flutter_parsed_text: ^2.2.0
  
  # --- Estado ---
  provider: ^6.1.2
  share_plus: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

# Configuración de Iconos
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoapp.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/logoapp.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/logoapp.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logoapp.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/